#!/usr/bin/env python3
"""
split_toolbox_config.py

Extracts the AlloyDB + MySQL portion of gcp_deploy/tools_db/tools.yaml into
a standalone tools_cloudrun.yaml for the new, second Toolbox instance
(mcp_toolbox_cloudrun.tf). Run this from the project root, same place every
other patch script in this project runs from:

    python3 split_toolbox_config.py

Deliberately does NOT touch or remove anything from the original
tools.yaml -- the VM's Toolbox keeps whatever it already has, including any
alloydb_*/mysql_* tool definitions that happen to already be in there. That
config becomes simply unused dead weight on the VM once
apply_toolbox_split_code.py is deployed (db_tools.py stops asking the VM's
Toolbox for those tools at all, regardless of whether it could technically
still serve them), which is strictly safer than trying to also strip it out
here -- there's no anchor-matching risk against a file this script doesn't
need to modify.

Output: gcp_deploy/tools_db/tools_cloudrun.yaml, containing:
  - every `kind: source` doc for alloydb-db / mysql-db (if present)
  - every `kind: tool` doc whose `source:` is alloydb-db or mysql-db
  - every `kind: toolset` doc whose tools all resolve to one of those tools
    (a toolset that mixes engines, if any exist, is left out with a warning
    printed -- toolsets aren't load-bearing for db_tools.py, which loads
    tools by name directly, so dropping one is safe; it's flagged rather
    than silently guessed at)

${VAR}-style placeholders in the source blocks (host/port/user/password)
are left AS-IS in the output, exactly like the original tools.yaml -- this
project already found Toolbox's own ${VAR} substitution unreliable for at
least one source/field combination (see database.tf's metadata_startup_script
comment on ${ORACLE_PASSWORD}), so the deploy step resolves these with a
literal sed pass before the file goes into Secret Manager, the same proven
approach the VM already uses. See README_TOOLBOX_SPLIT.md step 2-3.

Requires PyYAML (pip install pyyaml --break-system-packages if missing).
"""
import sys

try:
    import yaml
except ImportError:
    sys.exit(
        "Missing PyYAML. Install it first:\n"
        "  pip install pyyaml --break-system-packages\n"
        "then re-run this script."
    )

SRC_PATH = "gcp_deploy/tools_db/tools.yaml"
OUT_PATH = "gcp_deploy/tools_db/tools_cloudrun.yaml"
SPLIT_SOURCES = {"alloydb-db", "mysql-db"}

with open(SRC_PATH) as f:
    docs = list(yaml.safe_load_all(f))

docs = [d for d in docs if d]  # drop any blank documents from stray '---' separators

source_docs = [d for d in docs if d.get("kind") == "source" and d.get("name") in SPLIT_SOURCES]
found_sources = {d["name"] for d in source_docs}
if not found_sources:
    sys.exit(
        f"Found no 'kind: source' doc named alloydb-db or mysql-db in {SRC_PATH}.\n"
        f"Nothing to split -- either those sources use different names in your "
        f"copy of tools.yaml (check for a naming mismatch and re-run with the "
        f"SPLIT_SOURCES set at the top of this script adjusted), or this file "
        f"needs to be pasted back for a corrected script."
    )
print(f"Found source(s): {sorted(found_sources)}")

tool_docs = [d for d in docs if d.get("kind") == "tool" and d.get("source") in SPLIT_SOURCES]
tool_names = {d["name"] for d in tool_docs}
print(f"Found {len(tool_docs)} tool(s): {sorted(tool_names)}")

toolset_docs = []
skipped_toolsets = []
for d in docs:
    if d.get("kind") != "toolset":
        continue
    tools = set(d.get("tools", []))
    if not tools:
        continue
    if tools <= tool_names:
        toolset_docs.append(d)
    elif tools & tool_names:
        skipped_toolsets.append(d["name"])

if skipped_toolsets:
    print(
        f"WARNING: skipping {len(skipped_toolsets)} toolset(s) that mix split "
        f"and non-split tools (not load-bearing -- db_tools.py loads tools by "
        f"name, not by toolset): {skipped_toolsets}"
    )

out_docs = source_docs + tool_docs + toolset_docs
if not out_docs:
    sys.exit("Nothing extracted -- aborting without writing anything.")

with open(OUT_PATH, "w") as f:
    f.write(
        "# Generated by split_toolbox_config.py from tools.yaml -- do not hand-edit\n"
        "# without re-running the split, or the two files will drift.\n"
        "#\n"
        "# Config for the second Toolbox instance (mcp_toolbox_cloudrun.tf),\n"
        "# dedicated to AlloyDB + MySQL so an Oracle VM outage can no longer\n"
        "# blind their telemetry too (see apply_toolbox_split_code.py). ${VAR}\n"
        "# placeholders below still need literal values resolved before this\n"
        "# goes into Secret Manager -- see README_TOOLBOX_SPLIT.md step 3.\n"
    )
    yaml.safe_dump_all(out_docs, f, sort_keys=False, default_flow_style=False)

print(f"\nOK: wrote {OUT_PATH} ({len(out_docs)} documents).")
print("Next: README_TOOLBOX_SPLIT.md step 3 -- resolve the ${VAR} placeholders")
print("with real AlloyDB/MySQL connection values, then push the result to")
print("Secret Manager as the toolbox-alloydb-mysql-config secret version.")
